services:
  pricetracker:
    build:
      context: .
      dockerfile: Dockerfile
    image: arrjunpradeep/pricetracker:latest
    ports:
      - "3369:3369"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:13.15-alpine
    ports:
      - "5432:5432"
    env_file: 
      - .env